title: Nathan's Blog
description: This is my personal blog. I will write about my research and life.
url: https://i-am-wonseoklee.github.io

theme: just-the-docs

plugins:
  - jekyll-default-layout

math: mathjax

callouts:
  highlight:
    color: purple
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: yellow
  warning:
    title: Warning
    color: red